# Generated by Django 5.1.1 on 2025-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('professor', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_courses', to='courses.course')),
            ],
        ),
    ]
