# Generated by Django 5.1.1 on 2025-12-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_time',
            field=models.CharField(default='امتحان نامشخص', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
