# Generated by Django 5.1.1 on 2025-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_exam_time_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('GENERAL', 'عمومی'), ('PRACTICAL', 'عملی'), ('CORE', 'اصلی'), ('SPECIALIZED', 'تخصصی')], default='GENERAL', max_length=20),
            preserve_default=False,
        ),
    ]
