# Generated by Django 5.1.1 on 2025-12-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_course_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["code"],
                "verbose_name": "درس",
                "verbose_name_plural": "دروس",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="ظرفیت"),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="کد درس"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("THEORETICAL", "نظری"),
                    ("PRACTICAL", "عملی"),
                    ("GENERAL", "عمومی"),
                    ("ELECTIVE", "اختیاری"),
                ],
                default="THEORETICAL",
                max_length=20,
                verbose_name="نوع درس",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="exam_time",
            field=models.CharField(max_length=255, verbose_name="زمان امتحان"),
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(max_length=255, verbose_name="مکان"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام درس"),
        ),
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_courses",
                to="courses.course",
                verbose_name="پیش\u200cنیازها",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="professor",
            field=models.CharField(max_length=255, verbose_name="استاد"),
        ),
        migrations.AlterField(
            model_name="course",
            name="time",
            field=models.CharField(max_length=255, verbose_name="زمان"),
        ),
        migrations.AlterField(
            model_name="course",
            name="units",
            field=models.PositiveIntegerField(verbose_name="تعداد واحد"),
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor", models.CharField(max_length=255, verbose_name="استاد")),
                (
                    "class_number",
                    models.CharField(max_length=50, verbose_name="شماره کلاس"),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="ظرفیت")),
                (
                    "enrolled_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد ثبت\u200cنام"
                    ),
                ),
                (
                    "class_time",
                    models.CharField(max_length=255, verbose_name="زمان کلاس"),
                ),
                (
                    "exam_time",
                    models.CharField(max_length=255, verbose_name="زمان امتحان"),
                ),
                (
                    "semester",
                    models.CharField(
                        default="1404-1", max_length=50, verbose_name="نیمسال"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="courses.course",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلاس",
                "verbose_name_plural": "کلاس\u200cها",
                "ordering": ["course__code", "class_number"],
                "unique_together": {("course", "class_number", "semester")},
            },
        ),
    ]
