# Generated by Django 5.1.1 on 2025-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_migrate_course_data_to_offerings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="ظرفیت"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="exam_time",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="زمان امتحان"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="مکان"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="professor",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="استاد"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="time",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="زمان"
            ),
        ),
    ]
